// C++ STL
#include <algorithm>
#include <bit>
#include <charconv>
#include <fstream>
#include <sstream>
#include <vector>

// CGV framework core
#include <cgv/base/register.h>
#include <cgv/utils/dir.h>
#include <cgv/utils/file.h>

// local includes
#include "arclen/main.h"


namespace otv::fmt {

// Implementation details.
namespace {

using std::operator""sv, std::operator""s;

/// Empty class that prevents accidental copies.
struct nocopy {
	nocopy() = default;
	// Forbid copying.
	nocopy(nocopy const&) = delete;
	auto operator=(nocopy const&) = delete;
	// Allow moving.
	nocopy(nocopy&&) = default;
	auto operator=(nocopy&&) -> nocopy& = default;
};

//// Logging #######################################################################################

/// Marks messages generated by this loader.
#define LOG_TAG "\x1b[1m[fmt::jtf20]\x1b[m"

// Mark messages by severity.
#define LOG_ERROR   "\x1b[1;31m[error]\x1b[m"
#define LOG_WARNING "\x1b[1;33m[warning]\x1b[m"

/// Stream arguments to `std::clog`.
template<typename... Args>
void log(Args&&... args)
{
	(std::clog << ... << std::forward<Args>(args));
}

//// Configuration #################################################################################

/// Arguments influencing how trajectories are loaded.
/// Read from the dataset's root file.
struct config : nocopy {
	/// For every timestep, no more than this many particles will be read.
	/// The final number of trajectories may differ.
	uint32_t max_particles = std::numeric_limits<uint32_t>{}.max();
	/// Segments are generated between positions whose distance is greater than the simulation
	/// domain's diagonal extent times this factor.
	float seg_threshold = 1e-3;
	/// If for any coordinate the difference between subsequent positions of a particle is greater
	/// than the simulation domain's extent times this factor, its trajectory is split.
	float split_threshold = 0.9;

	/// Read configuration values from a file.
	[[nodiscard]] static auto from_file(std::istream& file) -> config;

private:
	/// The type of every setting is an array of one of these,
	enum class scalar_type : uint8_t {
		u32, // 32-bit unsigned integer
		f32, // 32-bit floating point number
	};
	/// Describes a setting's type and offset within `config`.
	struct setting {
		uint8_t     offset;
		scalar_type type   = {};
		uint8_t     extent = 0;
	};
	/// The identifier with which a setting is assigned.
	static constexpr auto names = std::to_array({
		"max_particles"sv,
		"seg_threshold"sv,
		"split_threshold"sv,
	});
	/// Type and offset of every setting.
	static const std::array<setting, names.size()> settings;
};

// Must be initialized outside the class so we can use `offsetof`.
constexpr auto config::settings = std::to_array<setting>({
	{offsetof(config, max_particles),   scalar_type::u32, 1},
	{offsetof(config, seg_threshold),   scalar_type::f32, 1},
	{offsetof(config, split_threshold), scalar_type::f32, 1},
});

auto config::from_file(std::istream& file) -> config {
	// Read file into string.
	file.exceptions(std::ios::badbit);
	auto buf = std::stringstream{};
	file >> buf.rdbuf();

	// Ensure that the text ends with a newline to simplify parsing.
	buf << '\n';

	// Parse settings, one per line.
	auto text   = buf.view(); // Remaining text.
	auto line   = size_t{0}; // Line number, starting at 1.
	auto tokens = std::vector<std::string_view>{}; // Words in the current line.
	auto cfg    = config{}; // Result.

	while (!text.empty()) { // For each line:
		++line;

		// Split line into words.
		tokens.clear();
		while (true) { // For each token:
			// Skip whitespace.
			text.remove_prefix(text.find_first_not_of(' '));

			// Handle special tokens.
			switch (text.front()) {
			case '#': // Comment: Skip the rest of this line, then exit the token loop.
				text.remove_prefix(text.find('\n') + 1);
				goto end_of_line;
			case '\n': // End of line: Exit token loop.
				text.remove_prefix(1);
				goto end_of_line;
			default:;
			}

			// Split off token from the text.
			auto const token = text.substr(0, text.find_first_of(" \n"));
			text.remove_prefix(token.length());
			tokens.push_back(token);
		} end_of_line:

		// Skip empty lines.
		if (tokens.empty()) continue;

		// The line's first word identifies the setting.
		// Check that it is defined and retrieve its descriptor.
		auto const idx = std::find(names.begin(), names.end(), tokens[0]) - names.begin();
		if (idx == names.size()) {
			log(LOG_WARNING" in line ",line,": Unknown setting ",tokens[0],".\n");
			continue;
		}
		auto const stg = settings[idx];

		// The remaining words are treated as values assigned to the setting,
		// Check that their number is as expected.
		if (tokens.size() - 1 != stg.extent) {
			auto txt_arguments = "arguments"sv;
			txt_arguments.remove_suffix(stg.extent == 1);
			log(LOG_ERROR" in line ",line,": ",tokens[0]," takes ",stg.extent," ",txt_arguments,
				", got ",tokens.size() - 1,".\n");
			continue;
		}

		// Parse each value and store it in the result configuration.
		auto const invalid_value = [&](uint8_t argn, std::string_view type) {
			log(LOG_ERROR" in line ",line,": Argument #",argn + 1,
				" does not match the expected type ",type,".\n");
		};
		auto const member = reinterpret_cast<std::byte*>(&cfg) + stg.offset;
		auto const args   = &tokens[1];
		switch (stg.type) {
		case scalar_type::u32:
			for (auto argn = 0; argn < stg.extent; ++argn)
				if (std::from_chars(
					&*args[argn].cbegin(),
					&*args[argn].cend(),
					reinterpret_cast<uint32_t*>(member)[argn]
				).ec != std::errc{})
					invalid_value(argn, "u32");
			break;
		case scalar_type::f32:
			for (auto argn = 0; argn < stg.extent; ++argn)
				if (std::from_chars(
					&*args[argn].cbegin(),
					&*args[argn].cend(),
					reinterpret_cast<float*>(member)[argn]
				).ec != std::errc{})
					invalid_value(argn, "f32");
			break;
		}
	}

	return cfg;
}

//// Deserialization ###############################################################################
//// Generics ======================================================================================

/// Workaround for CWG2518/P2593R1, taken from
/// https://en.cppreference.com/w/cpp/language/static_assert.html
template <class>
constexpr auto template_false = false;

/// Members of a serialized record in the Fortran binary dump.
template<typename T>
struct serialized
{
	static_assert(template_false<T>, "Type T cannot be serialized directly.");
};

/// Serialized representation of a scalar type.
/// This is the primitive from which all other serializations are built.
/// Compared to plain scalars, the serialized type requires no alignment and is always
/// little-endian.
template<typename T> requires (std::is_arithmetic_v<T> || std::is_enum_v<T>)&& (sizeof(T) <= 8)
struct serialized<T>
{
private:
	/// The bytes that make up the serialized value in little-endian order.
	/// Using a byte array avoids the alignment required by `uint_t`.
	std::array<std::byte, sizeof(T)> bytes;

public:
	/// Deserialize the value by copying its bytes into native alignment and endianness, then
	/// reinterpreting them via `bit_cast`.
	[[nodiscard]] constexpr auto get() const noexcept -> T
	{
		// Fix endianness.
		auto le_bytes = bytes;
		if constexpr (std::endian::native != std::endian::little)
			std::reverse(le_bytes.begin(), le_bytes.end());
		return std::bit_cast<T>(le_bytes);
	}
};

/// Serialize a fixed-size array by serializing each element individually.
template<typename T> requires std::is_bounded_array_v<T>
	&& requires {typename serialized<std::remove_extent_t<T>>;}
struct serialized<T> {
	/// Type of each element in the array, unserialized.
	using elem_t = std::remove_extent_t<T>;
	/// Number of elements in the array.
	static constexpr auto extent = std::extent_v<T>;

private:
	/// Each element is serialized individually.
	std::array<serialized<elem_t>, extent> elems;

public:
	/// Deserialize all elements into a new array.
	[[nodiscard]] constexpr auto get() const noexcept -> std::array<elem_t, extent>
	{
		std::array<elem_t, extent> result;
		std::ranges::transform(elems, result.begin(), [](auto elem) {return elem.get();});
		return result;
	}
};


/// A serialized record in the Fortran binary dump.
/// Consists of serialized members preceded and followed by their total size as a serialized 32-bit
/// unsigned integer.
template<typename T> requires requires {typename serialized<T>;}
struct record
{
private:
	serialized<uint32_t> header;
	serialized<T>        members;
	serialized<uint32_t> trailer;

public:
	/// Check that the stored record size matches the members type.
	[[nodiscard]] constexpr auto check() const noexcept -> bool
	{
		return header.get() == sizeof(members) && trailer.get() == sizeof(members);
	}

	/// Access members.
	[[nodiscard]] constexpr auto operator->() const noexcept -> serialized<T> const*
	{
		assert(check());
		return &members;
	}
};

//// Dataset format ================================================================================

/// General information about a timestep.
/// Stored at the beginning of each file.
struct timestep
{
	record<uint32_t> num_particles;
	record<double>   timestamp;
};

/// State of a single particle at a given timestep.
struct particle
{
	record<double[3]> position;
	record<double[3]> velocity;
	record<double[4]> orientation;
	record<double>    max_axis;
	record<double>    med_axis;
	record<double>    min_axis;
	record<uint32_t>  num_points;
};

} // namespace


/// Loads the record of an ellipsoid particle simulation by Jain, Tschisgale, and Fröhlich, 2020:
/// "Effect of particle shape on bedload sediment transport in case of small particle loading."
template<std::floating_point flt_type>
class jtf20 : public traj_format_handler<flt_type>
{
	using base = traj_format_handler<flt_type>;
	using typename base::real;
	using typename base::Vec3;
	using typename base::Vec4;

public:
	/// Return a name by which the dataset format can be identified.
	[[nodiscard]] auto format_name() const -> std::string const& override
	{
		static auto const name = "JTF 2020 Ellipsoid Particles"s;
		return name;
	}

	/// Datasets must be marked by adding a root file with the extension `jtf20` to the directory
	/// containing the timesteps.
	/// The root file is also used to configure how trajectories are loaded.
	[[nodiscard]] auto handled_extensions() const -> std::vector<std::string> const& override
	{
		static auto const ext = std::vector{"jtf20"s};
		return ext;
	}

	/// Try any file with the correct extension.
	[[nodiscard]] auto can_handle(std::istream&) const -> bool override
	{
		return true;
	}

	/// Load a dataset with a given root file.
	[[nodiscard]] auto read(std::istream&, DatasetOrigin, std::string const&)
		-> traj_dataset<real> override;

private:
	/// The state of a single particle at multiple timesteps as a struct of arrays.
	struct trace : nocopy {
		std::vector<Vec3> position;
		std::vector<Vec3> velocity;
		std::vector<Vec4> orientation;
		std::vector<real> max_axis;
		std::vector<real> med_axis;
		std::vector<real> min_axis;

		/// Allocate memory for a given number of timesteps.
		void reserve(size_t num_timesteps = 0)
		{
			position.reserve(num_timesteps);
			velocity.reserve(num_timesteps);
			orientation.reserve(num_timesteps);
			max_axis.reserve(num_timesteps);
			med_axis.reserve(num_timesteps);
			min_axis.reserve(num_timesteps);
		}
	};

	/// Data extracted from the binary files.
	struct simulation : nocopy {
		/// The timestamp of each timestep.
		std::vector<real> timestamps;
		/// The state of each particle at each timestep.
		/// All traces have the same length, which is identical to the length of `timestamps`.
		std::vector<trace> traces;
		/// Size of the axis-aligned bounding box containing every particle at every timestep.
		Vec3 extent;
	};

	/// Deserialize timesteps.
	/// Files must be ordered by timestamp.
	[[nodiscard]] auto read_simulation(std::span<std::string const> files, config const&)
		-> simulation;

	/// Segment deserialized particle traces into trajectories and store them in the format required
	/// by OnTubeVis.
	void gen_trajectories(simulation&&, config const&, traj_dataset<real>& dataset);
};


template<std::floating_point flt_type>
auto jtf20<flt_type>::read(
	std::istream& index,
	DatasetOrigin,
	std::string const& path
) -> traj_dataset<real>
{
	// Read config file.
	log(LOG_TAG" Reading config file ",path,"\n");
	auto const config = config::from_file(index);

	// Enumerate binary files: One per timestep.
	auto files = std::vector<std::string>{};
	cgv::utils::dir::glob(cgv::utils::file::get_path(path), files, "*.bin");

	// Sort files by name and thus time.
	std::sort(files.begin(), files.end());

	// Deserialize particle traces.
	auto sim = read_simulation({files.begin(), files.end()}, config);

	if (sim.timestamps.size() <= 2) {
		log(LOG_ERROR" At least two timesteps are required to generate trajectories.\n");
		return {};
	}

	// Convert traces to trajectories.
	auto ds = traj_dataset<real>{"JTF 2020 Ellipsoid Particle Simulation", path};
	gen_trajectories(std::move(sim), config, ds);

	// Configure dataset.
	ds.set_mapping({{
		{VisualAttrib::POSITION, {"position"}},
		// {VisualAttrib::TANGENT,  {"tangent"}},
	}});
	base::arclen_fn(ds) = otv::arclen::linear_parametrization<real>;
	return ds;
}

template<std::floating_point flt_type>
auto jtf20<flt_type>::read_simulation(std::span<std::string const> files, config const& config)
	-> simulation
{
	static constexpr auto inf = std::numeric_limits<real>().infinity();

	// Result.
	auto sim = simulation{};
	sim.timestamps.reserve(files.size());

	auto prev_timestamp = -inf;

	// Track the axis-aligned bounding box of the particles' positions.
	auto bbox_min = Vec3{ inf};
	auto bbox_max = Vec3{-inf};

	// Read files.
	auto file = std::ifstream{};
	file.exceptions(std::ios::badbit | std::ios::failbit);

	log(LOG_TAG" Reading ",files.size()," data files.\n");
	for (auto i = size_t{0}; i < files.size(); ++i) {
		// Print progress update.
		log(i + 1,"/",files.size(),"\r");

		// Open file.
		file.open(files[i], std::ios::binary);

		// Read timestep header.
		timestep timestep;
		file.read(reinterpret_cast<char*>(&timestep), sizeof(timestep));

		if (!timestep.num_particles.check()) [[unlikely]] {
			log("\x1b[KSkip ",files[i],": Invalid header.\n");
			goto next_file;
		}{

		// Check timestamp order.
		auto const timestamp = timestep.timestamp->get();
		if (timestamp <= prev_timestamp) [[unlikely]] {
			log("\x1b[KSkip ",files[i],": Timestamp out of order.\n");
			goto next_file;
		}
		prev_timestamp = timestamp;
		sim.timestamps.push_back(timestamp);

		// First timestep: Allocate particle traces.
		if (sim.traces.empty()) {
			sim.traces.resize(std::min(timestep.num_particles->get(), config.max_particles));
			for (auto& trace : sim.traces) trace.reserve(files.size());
		}

		// Read particle state.
		for (auto& trace : sim.traces) {
			particle particle;
			file.read(reinterpret_cast<char*>(&particle), sizeof(particle));

			// Update bounding box.
			auto const pos = Vec3{cgv::dvec3{particle.position->get()}};

			for (auto i : {0, 1, 2}) {
				bbox_min[i] = std::min(bbox_min[i], pos[i]);
				bbox_max[i] = std::max(bbox_max[i], pos[i]);
			}

			// Append new state to trace.
			trace.position.push_back(pos);
			trace.velocity.push_back(cgv::dvec3{particle.velocity->get()});
			trace.orientation.push_back(cgv::dvec4{particle.orientation->get()});
			trace.max_axis.push_back(particle.max_axis->get());
			trace.med_axis.push_back(particle.med_axis->get());
			trace.min_axis.push_back(particle.min_axis->get());
		}

		} next_file:
		// Close the input stream so it can be reused for the next file.
		file.close();
	}

	log("\x1b[K" LOG_TAG" Loaded ",sim.timestamps.size()," timesteps for ",sim.traces.size(),
		" particles.\n");

	sim.extent = bbox_max - bbox_min;
	return sim;
}

template<std::floating_point flt_type>
void jtf20<flt_type>::gen_trajectories(
	simulation&&        sim,
	config const&       config,
	traj_dataset<real>& ds
) {
	log(LOG_TAG" Processing ",sim.timestamps.size()," timesteps for ",sim.traces.size(),
		" particles.\n");

	// Create attributes.
	auto position    = base::template add_attribute<Vec3>(ds, "position");
	// auto tangent     = base::template add_attribute<Vec4>(ds, "tangent");
	auto velocity    = base::template add_attribute<Vec3>(ds, "velocity");
	auto orientation = base::template add_attribute<Vec4>(ds, "orientation");
	auto max_axis    = base::template add_attribute<real>(ds, "max_axis");
	auto med_axis    = base::template add_attribute<real>(ds, "med_axis");
	auto min_axis    = base::template add_attribute<real>(ds, "min_axis");

	// Calculate thresholds.
	auto const seg_threshold   = config.seg_threshold * sim.extent.length();
	auto const split_threshold = real{config.split_threshold} * sim.extent;

	// Build trajectories.
	auto length       = real{0}; // Total length of all segments.
	auto num_segments = size_t{0}; // Total number of segments.
	// First node in the current trajectory.
	struct {unsigned timestep, pos_idx;} traj_begin = {0, 0};

	for (auto i = size_t{0}; i < sim.traces.size(); ++i) {
		auto trace = std::move(sim.traces[i]);

		// Print progress update.
		log(i,"/",sim.traces.size(),"\r");

		/// Particle position at the previous timestep, whether or not it is included in the
		/// trajectory.
		auto prev_pos = trace.position[0];

		/// The last position included in the trajectory.
		/// It is not yet stored in the dataset to avoid singular nodes that are not part of a
		/// segment.
		struct {unsigned timestep; Vec3 pos;} prev_node = {0, prev_pos};

		/// Actually store the last node in the dataset.
		auto const push_node = [&]() {
			auto const time = sim.timestamps[prev_node.timestep];
			position.data.append(prev_node.pos, time);
			// tangent.data.append({trace.velocity[prev_node.timestep], 0}, time);
			// Other attributes are copied contiguously at the end of the trace.
		};
		/// Create a segment between the previous node and the current position, which becomes the
		/// new `prev_node`.
		auto const push_segment = [&](unsigned ts) {
			// Write the previous node to memory.
			push_node();

			// Update segment count and length.
			auto const pos = trace.position[ts];
			length        += (pos - prev_node.pos).length();
			num_segments  += 1;

			// Remember the new node as the trajectory's current end.
			prev_node = {ts, pos};
		};
		/// Create a new trajectory containing all nodes since the previous call.
		auto const push_traj = [&](unsigned ts) {
			// Add a node at the last timestep in the trajectory, unless the resulting segment would
			// have length 0.
			if (prev_pos != prev_node.pos) push_segment(ts - 1);

			// Avoid empty trajectories.
			if (position.data.num() == traj_begin.pos_idx) return;

			// Write the trajectory's final node to memory.
			push_node();

			// Store each attribute's sample range.
			auto const end = position.data.num();
			base::trajectories(ds, position.attrib).push_back({
				traj_begin.pos_idx,
				end - traj_begin.pos_idx
			});

			auto const range = ::range{
				velocity.data.num() + traj_begin.timestep, ts - traj_begin.timestep};
			base::trajectories(ds, velocity.attrib).push_back(range);
			base::trajectories(ds, orientation.attrib).push_back(range);
			base::trajectories(ds, max_axis.attrib).push_back(range);
			base::trajectories(ds, med_axis.attrib).push_back(range);
			base::trajectories(ds, min_axis.attrib).push_back(range);

			// Start the next trajectory at the current timestamp.
			traj_begin = {ts, end};
		};

		// Start the first trajectory.
		traj_begin.timestep = 0;

		// Determine which timesteps to create nodes at.
		for (auto ts = 1u; ts < sim.timestamps.size(); ++ts) {
			auto const pos   = trace.position[ts];
			auto const delta = cgv::math::abs(pos - prev_pos);

			// End the current trajectory when the particle wraps around the simualtion domain.
			for (auto d : {0, 1, 2})
				if (delta[d] > split_threshold[d]) {
					push_traj(ts);
					prev_node = {ts, pos}; // Begin a new trajectory.
					goto next_timestep;
				}

			// Create a new node for the current timestep.
			if ((pos - prev_node.pos).length() > seg_threshold)
				push_segment(ts);

			next_timestep:
			prev_pos = pos;
		}

		// End the last trajectory.
		push_traj(static_cast<unsigned>(sim.timestamps.size()));

		// Ignore empty trajectories.
		if (prev_node.timestep == 0) continue;

		// Otherwise copy non-position attributes at the full original sample rate.
		auto const append_samples = [&]<typename T>(
			typename traj_attribute<real>::template container<T>& attr,
			std::vector<T> const& values
		) {
			attr.values.insert(attr.values.cend(), values.cbegin(), values.cend());
			attr.timestamps.insert(
				attr.timestamps.cend(),
				sim.timestamps.cbegin(),
				sim.timestamps.cend()
			);
		};

		append_samples(velocity.data, trace.velocity);
		append_samples(orientation.data, trace.orientation);
		append_samples(max_axis.data, trace.max_axis);
		append_samples(med_axis.data, trace.med_axis);
		append_samples(min_axis.data, trace.min_axis);
	}

	// Summarize trajectories.
	log("\x1b[K" LOG_TAG" Generated ",base::trajectories(ds, position.attrib).size(),
		" trajectories comprising ",num_segments," segments and ",position.data.num(),
		" samples.\n");
	base::set_avg_segment_length(ds, length / static_cast<real>(num_segments));
}


// Register handlers..
cgv::base::object_registration<jtf20<float>>  jtf20_reg_flt {"JTF 2020 Ellipsoid Particles Handler (float)"};
cgv::base::object_registration<jtf20<double>> jtf20_reg_dbl {"JTF 2020 Ellipsoid Particles Handler (double)"};

} // namespace otv::fmt
